# Generated by Django 4.2.10 on 2024-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GentsCollection',
            new_name='GentsCategory',
        ),
        migrations.RenameModel(
            old_name='LadiesCollection',
            new_name='LadiesCategory',
        ),
    ]
