# Generated by Django 4.2.10 on 2024-09-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_gents',
        ),
    ]
