# Generated by Django 4.2.10 on 2024-09-02 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_category_gents'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('autumn', 'Autumn'), ('spring', 'Spring')], default=datetime.datetime(2024, 9, 2, 6, 23, 23, 759328, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
